// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Service.BlockchainWallets.Services.FirstGeneration.ChronoBank.Models
{
    public partial class RegisterResponse
    {
        /// <summary>
        /// Initializes a new instance of the RegisterResponse class.
        /// </summary>
        public RegisterResponse() { }

        /// <summary>
        /// Initializes a new instance of the RegisterResponse class.
        /// </summary>
        public RegisterResponse(string contract = default(string))
        {
            Contract = contract;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "contract")]
        public string Contract { get; set; }

    }
}
