// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace LkeServices.Generated.QuantaApi.Models
{
    using System.Linq;

    public partial class IsQuantaUserResponse
    {
        /// <summary>
        /// Initializes a new instance of the IsQuantaUserResponse class.
        /// </summary>
        public IsQuantaUserResponse() { }

        /// <summary>
        /// Initializes a new instance of the IsQuantaUserResponse class.
        /// </summary>
        public IsQuantaUserResponse(bool? isQuantaUser = default(bool?))
        {
            IsQuantaUser = isQuantaUser;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "isQuantaUser")]
        public bool? IsQuantaUser { get; set; }

    }
}
